language: node_js
node_js:
  - '12'

cache:
  yarn: true
  directories:
    - public
    - .cache

script:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
